version: '{build}'

branches:
  # blacklist
  except:
    - gh-pages

os: Visual Studio 2015

environment:
  GTEST_REPEAT: 1

  matrix:
  - VldStackWalkMethod: fast
    Solution: vld_vs12.sln
  - VldStackWalkMethod: safe
    Solution: vld_vs12.sln
  - VldStackWalkMethod: fast
    Solution: vld_vs14.sln
  - VldStackWalkMethod: safe
    Solution: vld_vs14.sln

platform:
  - Win32
  - x64

configuration:
  - Debug_VldRelease
  - Debug_VldRelease_StaticCrt
  - Release
  - Release_StaticCrt

matrix:
  fast_finish: false

build_script:
- ps: |
    Write-Output "Configuration: $env:CONFIGURATION"
    Write-Output "Platform: $env:PLATFORM"
    msbuild /v:m /p:"Configuration=$env:CONFIGURATION" /p:Platform="$env:PLATFORM" "$env:Solution" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
- ps: |
    cd src\

    function Add-GTest-Result($testResult)
    {
        $testsuites = ([xml](get-content $testResult)).testsuites
        $anyFailures = $FALSE

        foreach ($testsuite in $testsuites.testsuite) {
            foreach ($testcase in $testsuite.testcase) {
                if ($testcase.failure) {
                    $time = ([double]$testcase.time * 1000)
                    Add-AppveyorTest $testcase.name -Outcome Failed -FileName $testsuite.name -Duration $time -ErrorMessage $testcase.failure.message
                    Add-AppveyorMessage "$($testcase.name) failed" -Category Error
                    $anyFailures = $TRUE
                }
                elseif ($testcase.skipped) {
                    Add-AppveyorTest $testcase.name -Outcome Ignored -Filename $testsuite.name
                }
                else {
                    $time = ([double]$testcase.time * 1000)
                    Add-AppveyorTest $testcase.name -Outcome Passed -FileName $testsuite.name -Duration $time
                }
            }
        }
        return $anyFailures
    }


    function Run-Tests($platform, $configuration)
    {
        $anyFailures = $FALSE
        $tests_path = ".\bin\$platform\$configuration\"

        # Run tests and upload results to AppVeyor one by one
        Get-ChildItem "$tests_path\*.exe" | foreach {
            $testfile = "$($_.FullName).xml"
            & $_.FullName "--gtest_output=`"xml:$testfile`""
            if (Test-Path $testfile)
            {
                $testsResult = Add-GTest-Result $testfile
                $anyFailures = $anyFailures -or $testsResult
            }
        }

        if ($anyFailures -eq $TRUE){
            Write-Output "Failing build as there are broken tests"
            $host.SetShouldExit(1)
        }
    }

    $suffix = if ($env:Solution -eq "vld_vs14.sln") { "v140" } else { "v120" }
    $folders = @{"Debug_VldRelease" = "Debug(Release)-$suffix"; "Debug_VldRelease_StaticCrt" = "Debug(Release)_StaticCrt-$suffix";
        "Release" = "Release-$suffix"; "Release_StaticCrt" = "Release_StaticCrt-$suffix"}
    Run-Tests "$env:PLATFORM" "$($folders[$env:CONFIGURATION])"
